export const VIETNAM_BANKS = [
    { shortName: 'Vietcombank', name: 'Ngân hàng TMCP Ngoại Thương Việt Nam' },
    { shortName: 'VietinBank', name: 'Ngân hàng TMCP Công Thương Việt Nam' },
    { shortName: 'BIDV', name: 'Ngân hàng TMCP Đầu Tư và Phát Triển Việt Nam' },
    { shortName: 'Agribank', name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam' },
    { shortName: 'Techcombank', name: 'Ngân hàng TMCP Kỹ Thương Việt Nam' },
    { shortName: 'MBBank', name: 'Ngân hàng TMCP Quân Đội' },
    { shortName: 'VPBank', name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng' },
    { shortName: 'ACB', name: 'Ngân hàng TMCP Á Châu' },
    { shortName: 'Sacombank', name: 'Ngân hàng TMCP Sài Gòn Thương Tín' },
    { shortName: 'SHB', name: 'Ngân hàng TMCP Sài Gòn - Hà Nội' },
    { shortName: 'HDBank', name: 'Ngân hàng TMCP Phát triển TP. Hồ Chí Minh' },
    { shortName: 'TPBank', name: 'Ngân hàng TMCP Tiên Phong' },
    { shortName: 'VIB', name: 'Ngân hàng TMCP Quốc Tế Việt Nam' },
    { shortName: 'MSB', name: 'Ngân hàng TMCP Hàng Hải Việt Nam' },
    { shortName: 'SeABank', name: 'Ngân hàng TMCP Đông Nam Á' },
    { shortName: 'OCB', name: 'Ngân hàng TMCP Phương Đông' },
    { shortName: 'Eximbank', name: 'Ngân hàng TMCP Xuất Nhập Khẩu Việt Nam' },
    { shortName: 'LienVietPostBank', name: 'Ngân hàng TMCP Bưu Điện Liên Việt' },
    { shortName: 'PVcomBank', name: 'Ngân hàng TMCP Đại Chúng Việt Nam' },
    { shortName: 'Bac A Bank', name: 'Ngân hàng TMCP Bắc Á' },
    { shortName: 'ABBank', name: 'Ngân hàng TMCP An Bình' },
    { shortName: 'Nam A Bank', name: 'Ngân hàng TMCP Nam Á' },
    { shortName: 'VietBank', name: 'Ngân hàng TMCP Việt Nam Thương Tín' },
    { shortName: 'VietCapital Bank', name: 'Ngân hàng TMCP Bản Việt' },
    { shortName: 'NCB', name: 'Ngân hàng TMCP Quốc Dân' },
    { shortName: 'KienLongBank', name: 'Ngân hàng TMCP Kiên Long' },
    { shortName: 'Saigonbank', name: 'Ngân hàng TMCP Sài Gòn Công Thương' },
    { shortName: 'PG Bank', name: 'Ngân hàng TMCP Xăng Dầu Petrolimex' },
    { shortName: 'Shinhan Bank', name: 'Ngân hàng TNHH MTV Shinhan Việt Nam' },
    { shortName: 'Woori Bank', name: 'Ngân hàng Woori Việt Nam' },
    { shortName: 'UOB', name: 'Ngân hàng United Overseas Bank' },
    { shortName: 'Standard Chartered', name: 'Ngân hàng TNHH MTV Standard Chartered Việt Nam' },
    { shortName: 'HSBC', name: 'Ngân hàng TNHH MTV HSBC (Việt Nam)' },
    { shortName: 'CitiBank', name: 'Ngân hàng Citibank Việt Nam' },
    { shortName: 'HongLeong Bank', name: 'Ngân hàng Hong Leong Việt Nam' },
    { shortName: 'Public Bank', name: 'Ngân hàng Public Bank Việt Nam' }
];
